import React from 'react';

const TermsOfService: React.FC = () => {
  return (
    <div className="policy-content">
      <h2 className="text-2xl font-bold mb-6">Terms of Service</h2>
      
      <p className="mb-4">Last Updated: {new Date().toLocaleDateString()}</p>
      
      <section className="mb-6">
        <h3 className="text-xl font-semibold mb-3">Introduction</h3>
        <p className="mb-3">
          Welcome to the Financial Freedom Calculator. These Terms of Service ("Terms") govern your use of our retirement planning calculator and related services. 
          By accessing or using our calculator, you agree to be bound by these Terms and our Privacy Policy.
        </p>
      </section>
      
      <section className="mb-6">
        <h3 className="text-xl font-semibold mb-3 text-red-700">Financial Advice Disclaimer</h3>
        <div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-3">
          <p className="mb-3 font-semibold">
            The Financial Freedom Calculator is provided for informational and educational purposes only. It is not intended to provide financial, investment, tax, or legal advice.
          </p>
          <p className="mb-3">
            The calculations, projections, and estimates provided by this tool are based on the information you input and various assumptions about market performance, inflation, and other economic factors. 
            These projections are hypothetical and do not guarantee future results.
          </p>
          <p>
            Before making any financial decisions, we strongly recommend consulting with a qualified financial advisor, accountant, or attorney who can provide personalized advice tailored to your specific circumstances.
          </p>
        </div>
      </section>
      
      <section className="mb-6">
        <h3 className="text-xl font-semibold mb-3">User Obligations</h3>
        <p className="mb-3">
          By using our calculator, you agree to:
        </p>
        <ul className="list-disc pl-6 mb-3 space-y-2">
          <li>Provide accurate information when using the calculator</li>
          <li>Use the calculator for lawful purposes only</li>
          <li>Not attempt to interfere with the proper functioning of the calculator</li>
          <li>Not attempt to decompile, reverse engineer, or disassemble the calculator</li>
          <li>Not use the calculator in any way that could damage, disable, or impair the service</li>
        </ul>
      </section>
      
      <section className="mb-6">
        <h3 className="text-xl font-semibold mb-3">Intellectual Property</h3>
        <p className="mb-3">
          The Financial Freedom Calculator, including its design, text, graphics, interfaces, and code, is protected by copyright, trademark, and other intellectual property laws. 
          You may not reproduce, distribute, modify, create derivative works from, publicly display, or exploit in any way any portion of the calculator without our prior written consent.
        </p>
      </section>
      
      <section className="mb-6">
        <h3 className="text-xl font-semibold mb-3">Limitation of Liability</h3>
        <p className="mb-3">
          To the maximum extent permitted by law, we shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including loss of profits, 
          data, or goodwill, resulting from your use of or inability to use the calculator.
        </p>
        <p className="mb-3">
          The calculator is provided on an "as is" and "as available" basis without any warranties of any kind, either express or implied, including but not limited to the implied 
          warranties of merchantability, fitness for a particular purpose, or non-infringement.
        </p>
        <p>
          We do not warrant that the calculator will function without interruption or errors, or that defects will be corrected.
        </p>
      </section>
      
      <section className="mb-6">
        <h3 className="text-xl font-semibold mb-3">Investment Risk Disclaimer</h3>
        <p className="mb-3">
          All investments involve risk, including the possible loss of principal. The value of investments can go down as well as up, and you may not get back the full amount you invested. 
          Past performance is not a guarantee of future results.
        </p>
        <p>
          The hypothetical results generated by our calculator assume consistent returns and do not account for market volatility, economic changes, tax implications, or other factors 
          that may significantly affect actual investment outcomes.
        </p>
      </section>
      
      <section className="mb-6">
        <h3 className="text-xl font-semibold mb-3">Modifications to Terms</h3>
        <p>
          We reserve the right to modify these Terms at any time. We will notify users of any material changes by posting the new Terms on this page and updating the "Last Updated" date.
          Your continued use of the calculator after any changes indicates your acceptance of the modified Terms.
        </p>
      </section>
      
      <section className="mb-6">
        <h3 className="text-xl font-semibold mb-3">Governing Law</h3>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of Hong Kong, without regard to its conflict of law provisions.
        </p>
      </section>
      
      <section className="mb-6">
        <h3 className="text-xl font-semibold mb-3">Contact Us</h3>
        <p>
          If you have any questions about these Terms of Service, please contact us at: contact@FIRECalculator.ai
        </p>
      </section>
    </div>
  );
};

export default TermsOfService; 